# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cp_lower_bound <- function(ys, ns, alpha) {
    .Call('_calibrationband_cp_lower_bound', PACKAGE = 'calibrationband', ys, ns, alpha)
}

cp_upper_bound <- function(ys, ns, alpha) {
    .Call('_calibrationband_cp_upper_bound', PACKAGE = 'calibrationband', ys, ns, alpha)
}

lower_bound <- function(isoy, cc, part_lwr, ind_to_block) {
    .Call('_calibrationband_lower_bound', PACKAGE = 'calibrationband', isoy, cc, part_lwr, ind_to_block)
}

upper_bound <- function(isoy, cc, part_upr, ind_to_block) {
    .Call('_calibrationband_upper_bound', PACKAGE = 'calibrationband', isoy, cc, part_upr, ind_to_block)
}

